/* INSERT authors */
insert into authors (author) values ('Drucie Goodbourn');
insert into authors (author) values ('Marcia Aggiss');
insert into authors (author) values ('Giovanni Bigg');
insert into authors (author) values ('Duffie Eynon');
insert into authors (author) values ('Anselma McKennan');
insert into authors (author) values ('Gert Kira');
insert into authors (author) values ('Clerc Djakovic');
insert into authors (author) values ('Stacee Elsy');
insert into authors (author) values ('Dorotea Bonhill');
insert into authors (author) values ('Minni Bunney');
insert into authors (author) values ('Berty Gandley');
insert into authors (author) values ('Raynard Tesdale');
insert into authors (author) values ('Joanna Hutfield');
insert into authors (author) values ('Dannie Glidder');
insert into authors (author) values ('Timmie Adshede');
insert into authors (author) values ('Fernando Neads');
insert into authors (author) values ('Teddy Guilliland');
insert into authors (author) values ('Paloma Grebert');
insert into authors (author) values ('Kristos Usher');
insert into authors (author) values ('Darcey Rohmer');
insert into authors (author) values ('Cristie Isacsson');
insert into authors (author) values ('Lindsay Coutthart');
insert into authors (author) values ('Helyn Schneidar');
insert into authors (author) values ('Bette-ann Askem');
insert into authors (author) values ('Dom Robuchon');

/* INSERT books */
insert into books (title, priceOld, price) values ('exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (title, priceOld, price) values ('utilize real-time interfaces', '$260.31', '$35.96');
insert into books (title, priceOld, price) values ('extend strategic e-services', '$272.00', '$151.04');
insert into books (title, priceOld, price) values ('iterate integrated solutions', '$271.58', '$141.40');
insert into books (title, priceOld, price) values ('cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (title, priceOld, price) values ('architect vertical ROI', '$282.54', '$102.61');
insert into books (title, priceOld, price) values ('disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (title, priceOld, price) values ('extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (title, priceOld, price) values ('integrate one-to-one systems', '$258.51', '$52.25');
insert into books (title, priceOld, price) values ('revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (title, priceOld, price) values ('enhance innovative e-services', '$256.54', '$160.98');
insert into books (title, priceOld, price) values ('maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (title, priceOld, price) values ('scale integrated architectures', '$257.66', '$32.97');
insert into books (title, priceOld, price) values ('e-enable frictionless web services', '$288.19', '$90.52');
insert into books (title, priceOld, price) values ('strategize B2B channels', '$232.27', '$44.83');
insert into books (title, priceOld, price) values ('syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (title, priceOld, price) values ('utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (title, priceOld, price) values ('cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (title, priceOld, price) values ('embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (title, priceOld, price) values ('target innovative paradigms', '$298.94', '$130.01');
insert into books (title, priceOld, price) values ('generate open-source e-business', '$276.57', '$113.25');
insert into books (title, priceOld, price) values ('implement user-centric e-markets', '$254.70', '$115.31');
insert into books (title, priceOld, price) values ('utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (title, priceOld, price) values ('e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (title, priceOld, price) values ('facilitate efficient eyeballs', '$232.30', '$131.48');

/* INSERT authors_books */
insert into authors_books (author_id, book_id) values (1, 1);
insert into authors_books (author_id, book_id) values (2, 2);
insert into authors_books (author_id, book_id) values (3, 3);
insert into authors_books (author_id, book_id) values (4, 4);
insert into authors_books (author_id, book_id) values (5, 5);
insert into authors_books (author_id, book_id) values (6, 6);
insert into authors_books (author_id, book_id) values (7, 7);
insert into authors_books (author_id, book_id) values (8, 8);
insert into authors_books (author_id, book_id) values (9, 9);
insert into authors_books (author_id, book_id) values (10, 10);
insert into authors_books (author_id, book_id) values (11, 11);
insert into authors_books (author_id, book_id) values (12, 12);
insert into authors_books (author_id, book_id) values (13, 13);
insert into authors_books (author_id, book_id) values (14, 14);
insert into authors_books (author_id, book_id) values (15, 15);
insert into authors_books (author_id, book_id) values (16, 16);
insert into authors_books (author_id, book_id) values (17, 17);
insert into authors_books (author_id, book_id) values (18, 18);
insert into authors_books (author_id, book_id) values (19, 19);
insert into authors_books (author_id, book_id) values (20, 20);
insert into authors_books (author_id, book_id) values (21, 21);
insert into authors_books (author_id, book_id) values (22, 22);
insert into authors_books (author_id, book_id) values (23, 23);
insert into authors_books (author_id, book_id) values (24, 24);
insert into authors_books (author_id, book_id) values (25, 25);
insert into authors_books (author_id, book_id) values (2, 4);
insert into authors_books (author_id, book_id) values (3, 4);
insert into authors_books (author_id, book_id) values (5, 4);
